spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/baas_demo
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 18081

logging:
  level:
    root: warn